# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c209315cdd5c34c67417ffb63eae4ade66234ccf5ca69546062cc4760c22f2d7d1a21c90eba5b255d783d8f26f63cbd3cee733bbbcdd3fba17784c39d1b1ac8

test:
  secret_key_base: bc76120f047bfb9f57f09ebc542075016fb5ad08ba7d791903f926082ab033d66ff5c752bbb532baab021887c1f629442747d4159e097f95ad6d72853122aa1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
